tag: prod

server:
  type: grpc
  host: localhost
  port: 50077
  deadline: 5

database:
  presence:
    type: dynamodb
    userTablename: presence-user-prod
    timeTablename: presence-time-prod

camera:
  deviceID: 0

notification:
  slack:
    apitoken: xoxb-1176373024038-1218304944912-3CLVhQrKAJXNe7fHVydbhKY7
    apis:
      send: https://slack.com/api/chat.postMessage