tag: dev

server:
  type: http
  host: localhost
  port: 8080
  deadline: 5

database:
  presence:
    type: dynamodb
    usertablename: presence-user-dev
    timetablename: presence-time-dev

camera :
  deviceID: 0

facebox :
  url: http://localhost:8080
  picturenumber: 3

notification:
  slack:
    apitoken: xoxb-1176373024038-1218304944912-wIeZgcdJ2GrTXWUC75hqVWeY
    apis:
      send: https://slack.com/api/chat.postMessage