tag: prod

server:
  type: http
  host: localhost
  port: 8080
  deadline: 5

database:
  presence:
    type: dynamodb
    userTablename: presence-user-prod
    timeTablename: presence-time-prod

camera:
  deviceID: 0

notification:
  slack:
    apitoken: xoxb-1176373024038-1218304944912-wIeZgcdJ2GrTXWUC75hqVWeY
    apis:
      send: https://slack.com/api/chat.postMessage